Repository prgrms-web-devcourse/slam-server, pull requests merged in 2021-12, with the labels that each got.

#3 Feature/slam 46 - 프로젝트 공통 기능 설정
  pom.xml
  src/main/java/org/slams/server/common/api/ApiResponse.java
  src/main/java/org/slams/server/common/api/CursorPageRequest.java
  src/main/java/org/slams/server/common/api/CursorPageResponse.java
  src/main/java/org/slams/server/common/config/WebMvcConfig.java
  src/main/java/org/slams/server/common/error/ErrorResponse.java
  src/main/java/org/slams/server/common/error/GlobalExceptionHandler.java
  src/main/java/org/slams/server/common/error/exception/BusinessException.java
  src/main/java/org/slams/server/common/error/exception/EntityNotFoundException.java
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/common/error/exception/InvalidValueException.java
Labels: 리뷰 요청, 백엔드

#2 FEATURE/SLAM-45 court,reservation entity 추가
  src/main/java/org/slams/server/court/entity/Court.java
  src/main/java/org/slams/server/court/entity/NewCourt.java
  src/main/java/org/slams/server/court/entity/Status.java
  src/main/java/org/slams/server/court/entity/Texture.java
Labels: 리뷰 요청

#9 Feature/slam 1 - OAuth2.0 카카오로 회원가입 및 로그인 구현
  pom.xml
  src/main/java/org/slams/server/common/config/JwtConfig.java
  src/main/java/org/slams/server/common/config/WebSecurityConfig.java
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/user/controller/UserController.java
  src/main/java/org/slams/server/user/dto/DefaultUserInfoResponse.java
  src/main/java/org/slams/server/user/entity/Position.java
  src/main/java/org/slams/server/user/entity/Role.java
  src/main/java/org/slams/server/user/entity/Skill.java
  src/main/java/org/slams/server/user/entity/User.java
  src/main/java/org/slams/server/user/exception/InvalidTokenException.java
  src/main/java/org/slams/server/user/exception/UserNotAuthenticatedException.java
  src/main/java/org/slams/server/user/exception/UserNotFoundException.java
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/oauth/jwt/Jwt.java
  src/main/java/org/slams/server/user/oauth/jwt/JwtAuthentication.java
  src/main/java/org/slams/server/user/oauth/jwt/JwtAuthenticationFilter.java
  src/main/java/org/slams/server/user/oauth/jwt/JwtAuthenticationToken.java
  src/main/java/org/slams/server/user/repository/UserRepository.java
  src/main/java/org/slams/server/user/service/OAuthUserService.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/main/resources/application.yml
Labels: 리뷰 요청, 백엔드

#10 Feature/slam 22 알람 조회하기
  src/main/java/org/slams/server/alarm/entity/Alarm.java
  src/main/java/org/slams/server/alarm/entity/AlarmType.java
  src/main/java/org/slams/server/chat/entity/ChatDetails.java
  src/main/java/org/slams/server/chat/entity/ChatTitle.java
  src/main/java/org/slams/server/chat/entity/UserCourtMapping.java
  src/main/java/org/slams/server/notification/controller/NotificationController.java
  src/main/java/org/slams/server/notification/convertor/NotificationConvertor.java
  src/main/java/org/slams/server/notification/dto/CursorRequest.java
  src/main/java/org/slams/server/notification/dto/NotificationRequest.java
  src/main/java/org/slams/server/notification/dto/NotificationResponse.java
  src/main/java/org/slams/server/notification/entity/Notification.java
  src/main/java/org/slams/server/notification/entity/NotificationMessageFormat.java
  src/main/java/org/slams/server/notification/entity/NotificationType.java
  src/main/java/org/slams/server/notification/repository/NotificationRepository.java
  src/main/java/org/slams/server/notification/service/NotificationService.java
  src/test/java/org/slams/server/chat/entity/ChatDetailsTest.java
  src/test/java/org/slams/server/chat/entity/ChatTitleTest.java
  src/test/java/org/slams/server/chat/entity/UserCourtMappingTest.java
  src/test/java/org/slams/server/notification/entity/NotificationTest.java
  src/test/java/org/slams/server/notification/service/NotificationServiceTest.java
Labels: 리뷰 요청, 백엔드

#15 Feature/slam 54 - 내 정보 조회 api
  src/main/java/org/slams/server/follow/repository/FollowRepository.java
  src/main/java/org/slams/server/user/controller/UserController.java
  src/main/java/org/slams/server/user/dto/response/MyProfileResponse.java
  src/main/java/org/slams/server/user/entity/User.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/user/controller/UserControllerTest.java
Labels: 리뷰 요청, 백엔드

#21 Feature/slam 6 - 회원 프로필 조회 api
  src/main/java/org/slams/server/user/controller/UserController.java
Labels: 리뷰 요청, 백엔드

#27 Feature/slam 7 - 팔로워 목록 무한스크롤로 조회 api
  src/main/java/org/slams/server/common/api/CursorPageRequest.java
  src/main/java/org/slams/server/common/utils/JSONObjectMapper.java
  src/main/java/org/slams/server/follow/controller/FollowController.java
  src/main/java/org/slams/server/follow/dto/FollowResponse.java
  src/main/java/org/slams/server/follow/entity/Follow.java
  src/main/java/org/slams/server/follow/repository/FollowRepository.java
  src/main/java/org/slams/server/follow/service/FollowService.java
  src/main/java/org/slams/server/user/service/OAuthUserService.java
  src/test/java/org/slams/server/follow/controller/FollowControllerTest.java
  src/test/java/org/slams/server/notification/service/NotificationServiceTest.java
Labels: 리뷰 요청, 백엔드

#28 Feature/slam 8 - 팔로잉 목록 무한스크롤로 조회 api
  src/main/java/org/slams/server/follow/controller/FollowController.java
  src/main/java/org/slams/server/follow/dto/FollowerResponse.java
  src/main/java/org/slams/server/follow/dto/FollowingResponse.java
  src/main/java/org/slams/server/follow/repository/FollowRepository.java
  src/main/java/org/slams/server/follow/service/FollowService.java
  src/test/java/org/slams/server/follow/controller/FollowControllerTest.java
Labels: 리뷰 요청, 백엔드

#34 Feature/slam 52 - 프론트와 백 웹소켓 통신 확인을 위한 더미데이터 입력
  src/main/java/org/slams/server/user/controller/UserController.java
  src/main/java/org/slams/server/user/dto/response/DefaultUserInfoResponse.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/user/controller/UserControllerTest.java
Labels: 백엔드, ⚠️급한 처리⚠️

#31 Feature/slam 9 - 팔로우 맺기, 취소하기 기능 구현
  src/main/java/org/slams/server/common/error/exception/EntityNotFoundException.java
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/follow/dto/FollowerResponse.java~develop
  src/main/java/org/slams/server/follow/dto/FollowerResponse.java~feat : 팔로잉 목록 무한 스크롤로 조회 api 구현
  src/main/java/org/slams/server/follow/exception/FollowAlreadyExistException.java
  src/main/java/org/slams/server/follow/exception/FollowNotFoundException.java
  src/main/java/org/slams/server/follow/repository/FollowRepository.java
  src/main/java/org/slams/server/follow/service/FollowService.java
  src/test/java/org/slams/server/follow/service/FollowServiceTest.java
Labels: 리뷰 요청, 백엔드

#33 Feature/slam 29 - 관리자가 사용자가 요청한 농구장 승인 또는 취소하기 api
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/court/controller/CourtController.java
  src/main/java/org/slams/server/court/dto/request/NewCourtRequest.java
  src/main/java/org/slams/server/court/dto/response/NewCourtResponse.java
  src/main/java/org/slams/server/court/entity/NewCourt.java
  src/main/java/org/slams/server/court/exception/NewCourtNotFoundException.java
  src/main/java/org/slams/server/court/exception/UserNotFoundException.java
  src/main/java/org/slams/server/court/service/CourtService.java
  src/main/java/org/slams/server/court/service/NewCourtService.java
  src/main/java/org/slams/server/follow/dto/FollowerResponse.java~develop~develop
  src/main/java/org/slams/server/follow/dto/FollowerResponse.java~develop~feat : 팔로잉 목록 무한 스크롤로 조회 api 구현
  src/main/java/org/slams/server/management/controller/ManagementController.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
  src/test/java/org/slams/server/management/controller/ManagementControllerTest.java
Labels: 리뷰 요청, 백엔드

#36 Feature/slam 52 - 앱 실행 시 기본 제공 정보(사용자 정보, 알람정보) api 완성
  src/main/java/org/slams/server/notification/dto/response/NotificationResponse.java
  src/main/java/org/slams/server/notification/repository/NotificationIndexRepository.java
  src/main/java/org/slams/server/notification/service/NotificationService.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/user/controller/UserControllerTest.java
Labels: 리뷰 요청, 백엔드

#38 Fix/rebase conflict - Rebase 충돌 해결
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/court/controller/CourtController.java
  src/main/java/org/slams/server/court/service/CourtService.java
  src/main/java/org/slams/server/favorite/service/FavoriteService.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
  src/test/java/org/slams/server/court/controller/CourtControllerTest.java
Labels: ⚠️급한 처리⚠️

#42 Feature/slam 28 - 사용자가 추가한 농구장 조회 api
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/court/exception/InvalidStatusException.java
  src/main/java/org/slams/server/court/repository/NewCourtRepository.java
  src/main/java/org/slams/server/court/service/NewCourtService.java
  src/main/java/org/slams/server/management/controller/ManagementController.java
  src/test/java/org/slams/server/management/controller/ManagementControllerTest.java
Labels: 리뷰 요청, 백엔드

#46 Fix/slam 69 - redirect_uri를 동적으로 설정할 수 있게 수정
  src/main/java/org/slams/server/common/config/WebSecurityConfig.java
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/oauth/jwt/JwtAuthenticationFilter.java
Labels: 백엔드, ⚠️급한 처리⚠️

#48 Feature/slam 70 - refactor : PUT, PATCH status code를 202(ACCEPTED)로 수정
  src/main/java/org/slams/server/user/controller/UserController.java
  src/test/java/org/slams/server/user/controller/UserControllerTest.java
Labels: 리뷰 요청, 백엔드

#49 Feature/slam 71 - response에 팔로우 여부 추가
  src/main/java/org/slams/server/common/error/exception/ErrorCode.java
  src/main/java/org/slams/server/user/controller/UserController.java
  src/main/java/org/slams/server/user/dto/response/UserProfileResponse.java
  src/main/java/org/slams/server/user/exception/SameUserException.java
  src/main/java/org/slams/server/user/service/UserService.java
  src/test/java/org/slams/server/user/controller/UserControllerTest.java
Labels: 백엔드, ⚠️급한 처리⚠️

#54 Fix/followDeleteError - @Modifying을 붙여서 에러 해결
  src/main/java/org/slams/server/follow/repository/FollowRepository.java
  src/main/java/org/slams/server/follow/service/FollowService.java
Labels: 백엔드, ⚠️급한 처리⚠️

#59 fix : 지난 예약 목록 조회 코드 수정
  src/main/java/org/slams/server/reservation/controller/ReservationController.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
Labels: ⚠️급한 처리⚠️

#60 Fix/expried reservation
  src/main/java/org/slams/server/reservation/dto/response/ReservationExpiredResponseDto.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
Labels: ⚠️급한 처리⚠️

#61 Feature/slam 73 - api에 접근 권한 설정 추가
  src/main/java/org/slams/server/common/config/WebSecurityConfig.java
  src/main/java/org/slams/server/court/controller/CourtController.java
  src/main/java/org/slams/server/court/service/CourtService.java
Labels: 리뷰 요청, 백엔드

#64 fix : toggle follow 수정
  src/main/java/org/slams/server/reservation/dto/response/ReservationResponseDto.java
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
Labels: ⚠️급한 처리⚠️

#67 Feature/slam 77 - cors allowed origin 환경변수 설정
  src/main/java/org/slams/server/common/config/CorsFilter.java
  src/main/java/org/slams/server/common/config/WebSocketConfig.java
Labels: 백엔드, ⚠️급한 처리⚠️

#70 Feature/slam 76 - 기존 빌드로 복구
  src/main/java/org/slams/server/common/query/DummyCourtQuery.java
Labels: ⚠️급한 처리⚠️

#77 Fix/login 100 - 관리자 권한 부여를 위한 이메일 제한
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/service/OAuthUserService.java
Labels: 백엔드, ⚠️급한 처리⚠️

#85 Fix/TokenVerfiyError - refactor : jwt 발급 시 email도 포함시키도록 수정
  src/main/java/org/slams/server/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/org/slams/server/user/oauth/jwt/Jwt.java
Labels: 백엔드, ⚠️급한 처리⚠️

#87 Test/follow hotfix
  src/main/java/org/slams/server/reservation/repository/ReservationRepository.java
  src/main/java/org/slams/server/reservation/service/ReservationService.java
Labels: ⚠️급한 처리⚠️
